In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [4]:
import numpy as np 
list_= ['1','2','3','4','5']
arry_list = np.array(object=list_)
print("Data type of each element in 'list_':")
for element in list_:
    print(type(element))
print("print a data type of array list")
for element in arry_list:
    print(type(element))

Data type of each element in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
print a data type of array list
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


 yes ther is diffrent data type 


In [6]:
import numpy as np
num_list =[[1,2,3],[4,5,6]]
num_arr =np.array(num_list)

In [10]:
print("data type of each  and every  num_list")
for sublist in  num_list:
    print(type(sublist))
for row in num_arr:
    for element in row:
        print(type(element))

data type of each  and every  num_list
<class 'list'>
<class 'list'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [15]:
import numpy as np
num_list =[[1,2,3],[4,5,6]]
num_arr =np.array(num_list)

shape = num_arr.shape
size=  num_arr.size
print("shape of num_arr ." ,shape)
print("size of num_arr", size)

shape of num_arr . (2, 3)
size of num_arr 6


In [17]:
import numpy  as np
zero_arr = np.zeros((3,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [21]:
import numpy  as np
identity_metrix = np.eye(5)
print(identity_metrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
